[tool.poetry]
name = "api"
version = "0.1.0"
description = "api for asf-hp-installer-chatbot"
authors = ["Solomon Yu <solomon.yu@nesta.org.uk>"]
readme = "README.md"
packages = [
    { include = "app" },
    { include = "rag", from = ".." },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = ">=2"
twilio = ">=9.2.4"
unstructured = {extras = ["pdf"], version = ">=0.15.9"}
nltk = "3.8.1"
langchain = ">=0.2.2"
langchain-text-splitters = ">=0.2.4"
langchain-anthropic = ">=0.1.23"
langchain-openai = ">=0.1.23"
langchain-community = ">=0.2.16"
langchain-core = ">=0.2.38"
qdrant-client = ">=1.11.1"
langfuse = ">=2.46.0"
ragas = "0.1.16"
torch = {version = "^2.3.0"}
torchvision = {version = "^0.18.0"}
transformers = "4.41.2"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
asf-hp-installer-chatbot = {path = "..", develop = true}
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
