[tool.poetry]
name = "api"
version = "0.1.0"
description = "api for asf-hp-installer-chatbot"
authors = ["Solomon Yu <solomon.yu@nesta.org.uk>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
asf-hp-installer-chatbot = {path = "..", develop = true}


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
