[tool.poetry]
name = "api"
version = "0.1.0"
description = "api for asf-hp-installer-chatbot"
authors = ["Solomon Yu <solomon.yu@nesta.org.uk>"]
readme = "README.md"
packages = [
    { include = "app" },
    { include = "rag", from = ".." },
    { include = "asf_hp_installer_chatbot", from = ".." },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
uvicorn = {extras = ["standard"], version = "0.23.2"}
langserve = {extras = ["server"], version = "0.3.1"}
pydantic = "2.9.2"
unstructured = {extras = ["pdf"], version = "0.17.2"}
nltk = ">=3.8.1"
langchain = ">=0.3.7"
langchain-text-splitters = ">=0.3.8"
langchain-anthropic = ">=0.3.0"
langchain-openai = ">=0.2.8"
langchain-community = ">=0.3.7"
langchain-core = ">=0.3.18"
qdrant-client = ">=1.14.2"
langfuse = ">=2.60.5"
ragas = "0.1.16"
torch = {version = "^2.7.0"}
torchvision = {version = "^0.22.0"}
transformers = ">=4.41.2"
numpy = "<2"

[tool.poetry.scripts]
chatbot = "rag.cli:cli"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
asf-hp-installer-chatbot = {path = "..", develop = true}
langchain-cli = ">=0.0.36"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
